apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersapi
  labels:
    app: usersapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usersapi
  template:
    metadata:
      labels:
        app: usersapi
    spec:
      containers:
        - name: usersapi
          image: usersapi:latest
          ports:
            - containerPort: 80
          env:
            - name: RabbitMQ__HostName
              valueFrom:
                configMapKeyRef:
                  name: usersapi-config
                  key: rabbitmq_host
            - name: RabbitMQ__UserName
              valueFrom:
                secretKeyRef:
                  name: usersapi-secret
                  key: rabbitmq_user
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: usersapi-secret
                  key: rabbitmq_pass
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: usersapi-secret
                  key: jwt_key
---
apiVersion: v1
kind: Service
metadata:
  name: usersapi
spec:
  selector:
    app: usersapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
