# Secret para JWT Key (compartilhado pelas APIs que usam autenticação)
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: microservices
type: Opaque
stringData:
  key: "Q7KcQm8B+8p4zZP0P5B9GZzQ3T6z0sZq6GQ0m2ZP9Ys="