# Secret para credenciais do RabbitMQ (compartilhado)
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: microservices
type: Opaque
stringData:
  username: "fiap"
  password: "fiap123"
