apiVersion: v1
kind: Service
metadata:
  name: sql-users-service
  namespace: microservices
spec:
  selector:
    app: sql-users
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP