apiVersion: v1
kind: ConfigMap
metadata:
  name: users-api-config
  namespace: microservices
  labels:
    app: users-api
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:80"