apiVersion: v1
kind: Secret
metadata:
  name: users-api-secret
  namespace: microservices
  labels:
    app: users-api
type: Opaque
stringData:
  connection-string: "Server=sql-users-service,1433;Database=UsersDb;User Id=sa;Password=StrongPassword!123;TrustServerCertificate=True;"